### PR TITLE
[process][darwin][openbsd][freebsd] Fix #795 don't truncate process names to 16 characters

### LINKED ISSUE #795: [process][darwin] Process names are truncated to 16 characters
**Describe the bug**
Process names are truncated to 16 characters

**To Reproduce**
```go
p, _ := process.NewProcess(pidOfProcessWithLongName)
pName, _ := p.Name() // pName is truncated
```

**Expected behavior**
Process names should be returned in full.

**Environment (please complete the following information):**
 - [x] Mac OS: 
```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
> uname -a
Darwin [redacted] 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Additional context**
Same or similar issue was reported for Linux in issue #300 and fixed in PR #303

### PR DESCRIPTION
**Pull request by Lomanic**
[process][darwin][openbsd][freebsd] Fix #795 don't truncate process names to 16 characters

### CODE REVIEW

File: process/process_test.go [hunk 1]
```diff
@@ -289,6 +291,51 @@ func Test_Process_Name(t *testing.T) {
...
+		t.Fatalf("unable to create temp dir %v", err)
+	}
+	defer os.RemoveAll(tmpdir) // clean up
+	tmpfilepath := filepath.Join(tmpdir, "looooooooooooooooooooong.go")
+	tmpfile, err := os.Create(tmpfilepath)
+	if err != nil {
+		t.Fatalf("unable to create temp file %v", err)
+	}
+
+	tmpfilecontent := []byte("package main\nimport(\n\"time\"\n)\nfunc main(){\nfor range time.Tick(time.Second) {}\n}")
```
Comment (shirou) [inline process/process_test.go]: :+1: At first, I think just a bash or powershell is enough, but go has portability and go compiler should be exist in test environment. so this approachi is best, I agree.
