### PR TITLE
[mem][linux] Fix #1002 only try to parse /proc/meminfo numeric values on fields we're interested in

### LINKED ISSUE #1002: `fillFromMeminfoWithContext` cannot parse `/proc/meminfo` with multi-valued fields
**Describe the bug**

The function `fillFromMeminfoWithContext` cannot parse `/proc/meminfo` on a particular configuration that has multi-valued fields in `/proc/meminfo`.

**To Reproduce**
I found this running the stock configuration of Telegraf on the router, and traced it back to just running:
```go
mem.VirtualMemory()
```

**Expected behavior**
Memory statistics should be parsed.

**Environment (please complete the following information):**
 - [ ] Windows: [paste the result of `ver`]
 - [x] Linux: [paste contents of `/etc/os-release` and the result of `uname -a`]
 - [ ] Mac OS: [paste the result of `sw_vers` and `uname -a`
 - [ ] FreeBSD: [paste the result of `freebsd-version -k -r -u` and  `uname -a`]
 - [ ] OpenBSD: [paste the result of `uname -a`]
This is specifically DD-WRT on kernel 4.4 running on an `armel` router:
```
root@DD-WRT:~# uname -a
Linux DD-WRT 4.4.187 #650 SMP PREEMPT Tue Aug 6 11:38:46 +04 2019 armv7l DD-WR
```
**Additional context**

Here are the complete contents of `/proc/meminfo` on this machine:
```
root@DD-WRT:~# cat /proc/meminfo
        total:    used:    free:  shared: buffers:  cached:
Mem:  260579328 136073216 124506112        0  4915200 94064640
Swap:        0        0        0
MemTotal:         254472 kB
MemFree:          121588 kB
MemShared:             0 kB
Buffers:            4800 kB
Cached:            91860 kB
SwapCached:            0 kB
Active:           106236 kB
Inactive:           8380 kB
MemAvailable:     210156 kB
Active(anon):      17956 kB
Inactive(anon):        0 kB
Active(file):      88280 kB
Inactive(file):     8380 kB
Unevictable:           0 kB
Mlocked:               0 kB
HighTotal:        131072 kB
HighFree:          66196 kB
LowTotal:         123400 kB
LowFree:           55392 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         17992 kB
Mapped:            37884 kB
Shmem:                 0 kB
Slab:               9076 kB
SReclaimable:       2700 kB
SUnreclaim:         6376 kB
KernelStack:         624 kB
PageTables:          396 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      127236 kB
Committed_AS:      24968 kB
VmallocTotal:    1949696 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
```

I checked a few other ARM systems as well as an amd64 system and do not see the first two lines on any of them.

### PR DESCRIPTION
**Pull request by Lomanic**
Also add mocked `VirtualMemory()` tests.

Fixes #1002

### CODE REVIEW

File: v3/mem/mem_linux.go [hunk 1]
```diff
@@ -73,86 +73,226 @@ func fillFromMeminfoWithContext(ctx context.Context) (*VirtualMemoryStat, *Virtu
...
-		case "Sreclaimable":
+		case "SReclaimable":
+			t, err := strconv.ParseUint(value, 10, 64)
+			if err != nil {
+				return ret, retEx, err
+			}
 			sReclaimable = true
 			ret.Sreclaimable = t * 1024
-		case "Sunreclaim":
+		case "SUnreclaim":
```
Comment (shirou) [inline v3/mem/mem_linux.go:189]: wow, didn't noticed, sorry. it is because replacing on v3.

**Review by shirou — APPROVED** [review]
Ignore unexpected line is good way. Thank you so much

File: v3/mem/mem_linux.go (hunk 1 above)
Comment (Lomanic) [reply v3/mem/mem_linux.go:189]: I found this regression when porting the v2 mock to v3. I plan (and already started) to add mocked tests to prevent regressions (and do a bit of test driven development for #881 and #990) for the cpu package on linux (parsing `/proc/cpuinfo`).

I'm not sure why you renamed these fields in v3 in fact.

Comment (shirou) [reply v3/mem/mem_linux.go:189]: I renamed all by using sed, and i didn't noticed this also replaced. sorry
