### PR TITLE
ignore /proc/filesystems errors on android

### LINKED ISSUE #727: disk.Partitions fails on Android 8
as of Android 8, `/proc/filesystems` is no longer readable:

```
open /proc/filesystems: permission denied
```

cc #371 #372

### PR DESCRIPTION
**Pull request by tmm1**
fixes #727 and makes `disk.Partitions(true)` work on Android O again.

### CODE REVIEW

**Comment by shirou** [comment]
I wonder ignoring the permission error makes `disk.Partitions(true)` work. `getFileSystems()` returns empty so no supported filesystem, nothing returns. So I agree to @Lomanic, it should handled from application side.

**Comment by tmm1** [comment]
> I wonder ignoring the permission error makes `disk.Partitions(true)` work.

Yes, it works.



> `getFileSystems()` returns empty so no supported filesystem, nothing returns.

Since we're passing `all=true`, the filesystems list does not matter.

File: disk/disk_linux.go [hunk 1]
```diff
@@ -244,7 +245,7 @@ func PartitionsWithContext(ctx context.Context, all bool) ([]PartitionStat, erro
 	}
 
 	fs, err := getFileSystems()
-	if err != nil {
+	if err != nil && runtime.GOOS != "android" {
```
Comment (tmm1) [inline disk/disk_linux.go]:
```suggestion
	if err != nil && all {
```

**Comment by tmm1** [comment]
I updated the PR to ignore `getFileSystem()` errors when `all=true` is passed.

**Comment by shirou** [comment]
Yah! You are true. When `all=true`, `getFileSystems()` return values is not used. so it can be ignored. Great point! Thank you so much!
