### PR TITLE
fix(net,linux): fix decodeaddress if Big Endian

### LINKED ISSUE #990: s390x support
I was building/executing tests for [vault](https://github.com/hashicorp/vault). There are some tests makes use of routines from https://github.com/shirou/gopsutil/blob/master/cpu/cpu_linux.go#L116 to read /proc/cpuinfo

I could build vault from source however thetwo tests are failing for s390x architecture ( with an error: Expected non-nil CPU value) as this arch's /proc/cpuinfo has different contents than intel x86.

Is there any plan to support s390x arch for https://github.com/shirou/gopsutil ?
Please let me know.

### PR DESCRIPTION
**Pull request by shirou**
fixes #990

Check endian when decode address.

### CODE REVIEW

**Comment by zhsj** [comment]
With this patch, `Test_Connections` pass on s390x, but a new test fails:

```
--- FAIL: TestDecodeAddress (0.00s)
    net_linux_test.go:173:
                Error Trace:    net_linux_test.go:173
                Error:          Not equal:
                                expected: "10.0.0.5"
                                actual  : "5.0.0.10"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -10.0.0.5
                                +5.0.0.10
                Test:           TestDecodeAddress
                Messages:       0500000A:0016
    net_linux_test.go:173:
                Error Trace:    net_linux_test.go:173
                Error:          Not equal:
                                expected: "127.0.0.1"
                                actual  : "1.0.0.127"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -127.0.0.1
                                +1.0.0.127
                Test:           TestDecodeAddress
                Messages:       0100007F:D1C2
FAIL
```

**Comment by shirou** [comment]
@zhsj fix tests. Could you try again?

**Comment by zhsj** [comment]
Now the tests have passed, except `TestCpuInfo`, but it's unrelated to this PR.

File: net/net.go [hunk 1]
```diff
@@ -271,3 +272,10 @@ func getIOCountersAll(n []IOCountersStat) ([]IOCountersStat, error) {
 
 	return []IOCountersStat{r}, nil
 }
+
+// IsLittleEndian checks if the current platform uses little-endian.
+// copied from https://github.com/ntrrg/ntgo/blob/v0.8.0/runtime/infrastructure.go#L16 (MIT License)
+func IsLittleEndian() bool {
```
Comment (Lomanic) [inline net/net.go:278]: do we want this function to be exported here?

Comment (shirou) [reply net/net.go]: Absolutely no! I have moved to `internal/common` because it may be used from other package. Thank you for pointing out!!
